### ISSUE TITLE
Tiles on edges of EarthWorks WMS layers are discolored

### ISSUE THREAD

**Issue by codyml** [cestastanford/imaginedsf#2]
Rapid Transit Plan, 1972: when you zoom into the NW corner of the map the tiling gets strange.  At first the tile just west of the Presidio gets lighter than its surroundings, while the ocean just west of that turns dark blue.  Zoomed in further, some greens and purples appear, too.  Don’t see the same effect on the map as it displays in EarthWorks.

Downtown Design Plan: similar issue--zooming in creates discolored tiles.  Here the tiles at the bottom of the map turn a reddish purple.  

Fulton Circle map has same issue

**Comment by codyml** [comment]
Update: there are still weirdly discolored tiles, but now they're the same as what appears on EarthWorks.

**Comment by krainc** [comment]
Update (info from Kim): the discolored tiles can be fixed on the ArcGIS/EarthWorks side, and either I or Kim will fix any discolored tiles we find.
