### ISSUE TITLE
Automatically open collapsible list items

### ISSUE THREAD

**Issue by krainc** [cestastanford/imaginedsf#25]
Have the collapsible item (which contains opacity bar) automatically appear after user clicks the checkbox. 
This lives in collapsible-list-item.vue.

**Comment by codyml** [comment]
> - Under collapsible-list-item.vue collapsibleItem, I set the data as:
> `data: () => ({ collapsed: collapsed() }),`
> then I added this method:
> ```javascript
> collapsed() {
>     mapEnabled = get( this.$store.getters.isMapEnabled(this.map))
>     if (mapEnabled) {
>         this.collapsed = true
>     } else {
>         this.collapsed = false
>         console.log('test')
>     }
> },
> ```
> But it's not doing anything --> I'm guessing it's because I wasn't sure how to retrieve whether the map was enabled or not. Is there a way to do that/does my method look ok?

@krainc what you have does make sense, but it's hard for me to tell exactly what's wrong without seeing the full diff.  Have you checked the Webpack shell output and the Chrome web inspector console for the error?  Could you push your branch to your remote and reply with a link to it?  Offhand:
- What does the `get()` call do?  With Vuex getters, you can just access the property or call the getter function to get the value: `mapEnabled = this.$store.getters.isMapEnabled(this.map)`
- It looks like you have some conflicting names.  I think you may have meant to do `data: () => ({ collapsed: this.collapsed() }),`, but even with that, data properties and methods are both accessible on `this` in Vue, so both your data property and your method are both `this.collapsed` and I think the behavior of that is undefined.  Maybe change the method to be called `setCollapsed`?
- What you put in the `data` arrow function is only how that property will be initially set.  Not sure without seeing the rest of the code, but what you have here would set the initial collapsed state based on whether the map is enabled or not, but after that it would only change if the user clicked it.  Was that what you meant to do?  If you want it to instead always reflect the map enabled state, you'll want to instead replace both the data property and the method with a single computed property:
```javascript
computed: {
    collapsed() { return this.$store.getters.isMapEnabled(this.map) },
},
```

But, I think the bigger issue is that this component doesn't have a `this.map`.  Components are sealed off from everything around them except for the Vuex state and things explicitly passed to them as props by their parent component.  So, one fix would be to add a `map` prop to the `collapsible-list-item` component and have the parent components that are rendering it (`[basemap-list-item](https://github.com/cestastanford/imaginedsf/blob/master/static-src/scripts/maps/components/basemap-list-item.vue)`, `[proposal-list-item](https://github.com/cestastanford/imaginedsf/blob/master/static-src/scripts/maps/components/proposal-list-item.vue)`) pass `map` to it.

However, conceptually I'm not sure that having `collapsible-list-item` have `map` as a prop makes that much sense.  View frameworks like Vue are there to help us make decoupled, reusable components that only deal with the data that affects them: the collapsible list item is supposed to just contain the code and styling that makes an item in a list collapsible, and giving it a `map` prop feels to me like it would be diluting it with something unrelated to its task.  And, this component is actually being reused in ways where `map` as a prop doesn't make sense: we use it in `[proposal-list-item](https://github.com/cestastanford/imaginedsf/blob/master/static-src/scripts/maps/components/proposal-list-item.vue)` as the top-layer collapsible list but also as the sub-lists for Photos & Drawings and actually as every list item inside the list.  Having each one of these require a "map" prop wouldn't make sense.

Instead, what if you changed the "collapsed" data to a prop on `collapsible-list-item`?  It is relevant to `collapsible-list-item` whether it's collapsed or not, and it leaves it up to the parent component to pass a `collapsed` prop based on whatever they want: it could be `this.$store.getters.isMapEnabled(this.map)`.  You could even set it up so the component has both a prop and a data: its parent can set it to be collapsed or not collapsed using props, but if its parent doesn't set it using props, it internally saves and sets its own collapsed state using its own data.

**Comment by krainc** [comment]
I tried making `collapsed` a prop and a data on `collapsible=list-item`, and passing the `collapsed` prop from `proposal-list-item` to it whenever the user clicks the checkbox to enable the map, but the functionality is still not what I intend. Everything just starts out as not collapsed now. I pushed my branch (with the latest updates) to my fork and here's the link: https://github.com/krainc/imaginedsf/tree/23-collapsible-items
