### ISSUE TITLE
Add a "Share" button for easier link sharing

### ISSUE THREAD

**Issue by codyml** [cestastanford/imaginedsf#52]

**Comment by cartosattva** [comment]
![image](https://user-images.githubusercontent.com/12202208/66511922-b71d9100-ea8c-11e9-9649-0958dbd4d8f0.png)

**Comment by codyml** [comment]
Button opens a modal with with the URL to copy
- "Copy to clipboard" button
- "Email" button

**Comment by codyml** [comment]
Design required: modal content

**Comment by codyml** [comment]
Button has tooltip
