### ISSUE TITLE
Update tooltip text of Zoom to full extents of active maps

### ISSUE THREAD

**Issue by cartosattva** [cestastanford/imaginedsf#59]
1. Let's retitle this to: Zoom to full extent of active maps

~2. in my experience, it seemed unexpected to have basemaps included in this function. Does it make sense to remove them from the calculation?~ Moved to #69.

~3. I also kinda wish I could zoom to each map individually with a small button to the right of each transparency slider. Thoughts?~ Moved to #70.

**Comment by codyml** [comment]
2. moved to #69
3. moved to #70
