### ISSUE TITLE
Add active maps badge on Proposal Maps tab

### ISSUE THREAD

**Issue by cartosattva** [cestastanford/imaginedsf#60]
I noticed this when the site first loads: it is confusing what map is being shown. The basemaps list in the corner attracts the eye... but that does not reflect the map state.  First, maybe we should auto minimize the basemaps list on load or when you switch tabs? Second, I wonder if a small red numerical badge on the proposal tab (a la ios style) might be useful when you are viewing the introduction or narratives sections?

**Comment by cartosattva** [comment]
just noticed that this would also be beneficial as a visual cue when a user clicks a state link in a narrative

**Comment by codyml** [comment]
- Is the initial view problem solved by having the Introduction be a modal (#73)?  Proposal Maps will now be the first panel view seen, so maybe it's clearer which maps are visible?  If so, should we leave the basemaps panel expanded on load?
- Can still add badge to Proposal Maps tab with # of enabled maps (not including map groups, right?)

Design required: badge appearance

**Comment by codyml** [comment]
Basemaps visible by default; add badge.
