### ISSUE TITLE
add WMTS support for basemaps

### ISSUE THREAD

**Issue by cartosattva** [cestastanford/imaginedsf#63]
I've created a styled base map in MapBox but I can't get it to show up in ISF ("Light basemap"). It appears that we need to configure Leaflet to support WMTS services.

Here is the style url: https://api.mapbox.com/styles/v1/steiner/cijxaq5h100d2qtkqrgtvvc54/wmts?access_token=pk.eyJ1Ijoic3RlaW5lciIsImEiOiIyT1NsejNjIn0.RTh9EHOG2cpFVPYMfC8wPQ

**Comment by codyml** [comment]
Not needed; Mapbox can serve tiles for Tile layer.
