### ISSUE TITLE
Reconfigure Eras to be their own content type; automatically sort by date

### ISSUE THREAD

**Issue by cartosattva** [cestastanford/imaginedsf#66]
It is hard to order the list manually unless you have the dates memorized or the date is in the title. But actually we don't want to use the dates in the titles because then they appear twice on the site.

Is there any situation where we wouldn't want them to be sorted automatically?

**Comment by codyml** [comment]
That all makes sense!  If we don't need manual sorting and can automatically sort by ascending start year, I could convert the Proposal Eras screen into a more standard post editing screen like we have for Maps and Map Groups.  You'd edit each Era on its own separate Edit Post screen and the main Proposal Eras screen would just be a list of titles, which would clean up the view a lot.  The order in the list would then not reflect the order displayed on the front-end; on the front-end they'd be sorted automatically by ascending start year.  Does that sound like a good solution?

**Comment by codyml** [comment]
Above plan sounds good.
