### ISSUE TITLE
Misc design updates from updated mockups

### ISSUE THREAD

**Issue by cartosattva** [cestastanford/imaginedsf#67]
see original mockup - it's not perfect but I think reducing overall would be nicer

**Comment by codyml** [comment]
- Update Proposal Maps panel styles
   - Add line below tabs
   - Update panel header
   - Adjust sizing/spacing of list items
- Update basemap control styles
   - Adjust sizing/spacing of list items when expanded
   - Add year when expanded
   - Adjust collapsed view
- Update tooltips
   - Add Zoom In/Zoom Out
   - Add Share
   - Enter an address to zoom ~in~ to that location
   - Make them smaller
- Update modal style
   - Move modals to be in the middle of the map area, not the full screen
   - Decrease left/right padding
   - Change title text style
   - Change button style

**Comment by codyml** [comment]
Also: change "showing 2 of 3 plans" to "show 2 hidden maps outside of visible area" with link that unchecks checkbox.  Also change "plan" to "map" in checkbox.
